name: Mushroom_CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "MLProject/mushrooms_preprocessed.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python Version 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"
        
    - name: Check Env
      run: |
        echo $CSV_URL
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run mlflow
      run: |
        mlflow run MLProject --env-manager=local

    - name: Save mlruns to repo
      run: |
        git config --global user.name ${{ secrets.username }}
        git config --global user.email ${{ secrets.email }}
        git add mlruns/
        git commit -m "Save mlruns from CI run"
        git push origin master
