name: Mushroom_CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "MLProject/mushrooms_preprocessed.csv"
  TARGET_VAR: "Mushroom"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python Version 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"
        
    - name: Check Env
      run: |
        echo $CSV_URL
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run mlflow
      run: |
        mlflow run MLProject --env-manager=local

    - name: Check mlruns dir
      run: |
        ls -R mlruns/

    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Build Docker Model
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "mushroom_model"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag mushroom_model ${{ secrets.DOCKER_HUB_USERNAME }}/mushroom_model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mushroom_model:latest

    - name: Save mlruns to repo
      run: |
        git config --global user.name "Refanz"
        git config --global user.email "refandasuryasaputra@gmail.com"
        git add mlruns/
        git commit -m "Save mlruns from CI run"
        git push origin master
